### ISSUE TITLE
Use CI for running tests

### ISSUE THREAD

**Issue by pconerly** [HenrikJoreteg/html-parse-stringify#29]
It'd be good to run our tests on a OSS-friendly CI somewhere for our own accountability. I'm inclined towards circleCI.

@kranges @frontmesh I'm gonna plan on doing this in a couple days, reply back if you have any objections.

**Comment by pconerly** [comment]
tried this out in #30

**Comment by frontmesh** [comment]
I believe travis is already used for this [.travis.yml]('https://github.com/HenrikJoreteg/html-parse-stringify/blob/master/.travis.yml')

**Comment by HenrikJoreteg** [comment]
in v2.0.0 i removed the whole zuul  browser setup. This is all just string manipulation in JS, I don't feel the need to do cross-browser testing here. So now it's super easy to just run `npm test` and run this all in node. I don't we gain much from doing CI here. But, perhaps could be convinced otherwise 😅
