### ISSUE TITLE
Multi-line attributes don't parse correctly

### ISSUE THREAD

**Issue by alshdavid** [HenrikJoreteg/html-parse-stringify#36]
When trying to parse elements with multi-line attributes

something like

```html
<div 
  style="
    color: red;
    text-align: blue;
  "
></div>
```

The resulting attributes look like:
`result[0].attributes`
```json
{
  "color:": "",
  "red;": "",
  "text-align:": "",
  "blue;": ""
}
```

But should look like

```json
{
   style: "\ncolor: red;\ntext-align: blue;\n"
}
```

**Comment by HenrikJoreteg** [comment]
Hey! 👋  

There are lots of edge cases that won't be covered with this, which is why HTML parsing with regexes is generally discouraged (as outlined in the readme). This is meant for parsing HTML that follows strict rules, personally I'm of the opinion that not supporting multi-line attributes is ok. If you think there's a quick/easy fix here and would like to send a PR, i'm open to it, though.
